"""update deployment

Revision ID: 75a8d7515999
Revises: 6fe20a6a3166
Create Date: 2026-03-12 06:10:55.350207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75a8d7515999'
down_revision: Union[str, Sequence[str], None] = '6fe20a6a3166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('user_sessions', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'expires_at')
    op.drop_column('user_sessions', 'is_active')
    # ### end Alembic commands ###
