"""update models

Revision ID: 8da443285d6f
Revises: 30be0c85b80d
Create Date: 2026-03-12 05:38:33.814718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8da443285d6f'
down_revision: Union[str, Sequence[str], None] = '30be0c85b80d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('server_groups_group_id_fkey'), 'server_groups', type_='foreignkey')
    op.create_foreign_key(None, 'server_groups', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'server_groups', type_='foreignkey')
    op.create_foreign_key(op.f('server_groups_group_id_fkey'), 'server_groups', 'servers', ['group_id'], ['id'])
    # ### end Alembic commands ###
