"""update deployment

Revision ID: eae56562abab
Revises: ab94190f9c63
Create Date: 2026-03-12 06:05:43.856590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eae56562abab'
down_revision: Union[str, Sequence[str], None] = 'ab94190f9c63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('Asia/Kolkata'::text, now())"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
